# Generated by Django 4.1.1 on 2022-09-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CT', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
