# Generated by Django 4.1.1 on 2022-09-20 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CT', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
